### YamlMime:ModuleUnit
uid: learn.azure.choose-azure-services-sla-lifecycle.3-define-application-sla
title: Define your application SLA
metadata:
  description: "Learn about a few factors you might consider when defining your application SLA."
  ms.date: 09/14/2020
  author: tpetchel
  ms.author: thpetche
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 3
content: |
  [!include[](includes/3-define-application-sla.md)]