### YamlMime:ModuleUnit
uid: learn.azure.secure-network-connectivity-azure.6-configure-access-network-security-group
title: Exercise - Configure network access to a VM by using a network security group
metadata:
  description: Configure network access to a virtual machine running on Azure by using a network security group.
  ms.date: 09/14/2020
  author: tpetchel
  ms.author: thpetche
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: true
interactive: bash
durationInMinutes: 10
content: |
  [!include[](includes/6-configure-access-network-security-group.md)]